#!/bin/sh
#
# debianize the mathematica license server
#

# 1) zipfile must be provided manually 

ARCHIVE=$1

[ $ARCHIVE ] || abort "Need an archive to extract mathlm"

if [ "$2" ]; then
    ARCH=$2
else
    ARCH=`dpkg-architecture -qDEB_BUILD_ARCH`
fi

extract $ARCHIVE 

# lets assume there is only one shell script:
INSTALLER=`find $BUILD_DIR -name '*.sh'`

PACKAGE=mathlm
VERSION=$(sed -ne 's/label="\(Wolfram \)\?MathLM \([0-9.]\+\) for UNIX Installer Archive"/\2/p' "$INSTALLER")

PKG_DIR=$BUILD_DIR/${PACKAGE}-${VERSION}

# the extract subdir must not exist
yes e | sh $INSTALLER --nox11 --target $PKG_DIR --keep || true

debut_dh_make

# disable dh_strip (for cross-building):
debian_rules

build_architecture $ARCH

SOURCE_DIR=Unix/bin/Linux

[ "$ARCH" = "amd64" ] && SOURCE_DIR=Unix/bin/Linux-x86-64

for EXE in monitorlm mathlm; do
    debian_install $SOURCE_DIR/$EXE /usr/sbin
done

cat <<EOF > $PKG_DIR/debian/manpages
Unix/man/mathlm.1
Unix/man/monitorlm.1
EOF

echo /var/log/mathlm > $PKG_DIR/debian/dirs

add_debian_files

# postinst creates a mathlm account:
add_dependency adduser

debian_control Homepage http://www.wolfram.com/mathematica/
debian_control Section non-free/education

build_package

drop_result
