#!/bin/sh
#
# Debutant recipe for Mathematica license server mathlm debian package
#
# Copyright 2013-2022 GSI Helmholtzzentrum fuer Schwerionenforschung GmbH
#
# Authors:
#  Christopher Huhn    <c.huhn@gsi.de>
#  Bastian Neuburger   <b.neuburger@gsi.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# zipfile or .sh installer must be provided manually:
ARCHIVE=$1

[ "$ARCHIVE" ] || abort "Need an archive to extract mathlm"

if [ "$2" ]; then
    ARCH=$2
else
    ARCH=$(dpkg-architecture -qDEB_BUILD_ARCH)
fi

if [ "$(mime_type "$ARCHIVE")" = 'text/x-shellscript' ]; then
    INSTALLER=$ARCHIVE
else
    extract "$ARCHIVE"

    # lets assume there is only one shell script:
    INSTALLER=$(find "$BUILD_DIR" -name '*.sh')
fi

PACKAGE=mathlm
VERSION=$(sed -ne 's/label="\(Wolfram \)\?MathLM \([0-9.]\+\) for UNIX Installer Archive"/\2/p' "$INSTALLER")

PKG_DIR=$BUILD_DIR/${PACKAGE}-${VERSION}

# the extract subdir must not exist
yes e | sh $INSTALLER --nox11 --target $PKG_DIR --keep || true

debut_dh_make

# disable dh_strip (for cross-building):
debian_rules

build_architecture "$ARCH"

SOURCE_DIR=Unix/bin/Linux

[ "$ARCH" = "amd64" ] && SOURCE_DIR=Unix/bin/Linux-x86-64

for EXE in monitorlm mathlm; do
    debian_install $SOURCE_DIR/$EXE /usr/sbin
done

cat <<EOF > $PKG_DIR/debian/manpages
Unix/man/mathlm.1
Unix/man/monitorlm.1
EOF

echo /var/log/mathlm > "$PKG_DIR/debian/dirs"

add_debian_files

# postinst creates a mathlm account:
add_dependency adduser

debian_control Homepage http://www.wolfram.com/mathematica/
debian_control Section non-free/education

build_package

drop_result
