#!/bin/sh
#
# extract ICAclient package and repack it to be suitable for GSI
# 

#REVISION=1
# TARGET_RELEASE=`lsb_release -cs`
# ARCH=`dpkg-architecture -qDEB_HOST_ARCH`

# while getopts "v:t:a:" OPTION; do
#     case $OPTION in 
#         a)
#             ARCH=$OPTARG
#             ;;
#         t)
#             TARGET_RELEASE=$OPTARG
#             ;;
#     esac
# done

# shift $(($OPTIND - 1))


PKG=$1

# Does not work, needs manual download
#if [ -z $PKG ]; then
#    PKG=`fetch https://downloads.citrix.com/akdlm/8618/icaclient_13.0.0.256735_amd64.deb`
#fi

#extract "$ARCHIVE"

[ $PKG ] || abort "Need an archive (*.deb) to extract icaclient"

# icaclient comes as a Debian package but we repackage it: 
PKG_NAME=`dpkg-deb -I $PKG | sed -ne "s/ Package: //p"`

# determine version, add dbtnt suffix if missing:
VERSION=`dpkg-deb -I $PKG | sed -ne "s/ Version: //p"`
DEBIAN_FLAVOR=`lsb_release -cs`

MAJOR_VERSION=`echo $VERSION | cut -f1 -d.`
if ! expr "$VERSION" : ".*+dbtnt+${DEBIAN_FLAVOR}\.[0-9]\+$" > /dev/null; then
    VERSION="${VERSION}+dbtnt+${DEBIAN_FLAVOR}.${REVISION}"
fi

PKG_DIR="$BUILD_DIR/${PKG_NAME}-${VERSION}"

extract $PKG $PKG_DIR

# create package skeleton:
debut_dh_make

add_debian_files

# not all dependencies are resolvable (on Wheezy)
#echo "override_dh_shlibdeps:" >> ${PKG_DIR}/debian/rules

# keep the original copyright
cp $PKG_DIR/usr/share/doc/icaclient/copyright         $PKG_DIR/debian/

# append the original changelog:
zcat $PKG_DIR/usr/share/doc/icaclient/changelog.gz >> $PKG_DIR/debian/changelog


# modify the extracted debian/control:
( 
    #Build-depends: ia32-libs-gtk, libmotif4:i386, libspeex1, 
    cat <<EOF 
Source: icaclient
Build-depends: libgstreamer0.10-0:i386, libxerces-c3.1:i386
Maintainer: $DEBFULLNAME <$DEBEMAIL>

EOF
    grep -v "^\(Version\|Maintainer\|Installed-Size\): .*" $PKG_DIR/DEBIAN/control 
) > $PKG_DIR/debian/control 

# remove dependencies:
#sed -i -e "s/^\(Depends:\).*/\1/" $PKG_DIR/debian/control

# Squeeze/AMD64 needs a 32bit libmotif:
if [ "$TARGET_RELEASE" = "squeeze" -a "$ARCH" = "amd64" ]; then
    add_dependency ia32-libmotif4 nspluginwrapper
else
    if $MAJOR_VERSION -lt 13; then
        add_dependency libmotif4
        build_architecture i386
    fi
fi

# Fix paths
sed -e "s|opt/Citrix/ICAClient|usr/lib/ICAClient|g" \
    $PKG_DIR/usr/share/menu/icaclient > $PKG_DIR/debian/menu

if [ -d $PKG_DIR/usr/share/applications/ ]; then
    # only for 13.0
    sed -i -e "s|opt/Citrix/ICAClient|usr/lib/ICAClient|g;s| -icaroot| --icaroot|" \
        $PKG_DIR/usr/share/applications/*desktop
    echo "usr/share/applications/" >>  $PKG_DIR/debian/install
fi

# wfcmgr vanished in 13.0:
if [ -e $PKG_DIR/opt/Citrix/ICAClient/wfcmgr ]; then
    echo "/usr/lib/ICAClient/wfcmgr /usr/bin/icaclient" >> $PKG_DIR/debian/links
elif [ -e $PKG_DIR/opt/Citrix/ICAClient/selfservice ] ; then
    echo "/usr/lib/ICAClient/selfservice /usr/bin/icaclient" \
         >> $PKG_DIR/debian/links
fi

# this will be linked to /etc/ssl/certs/:
rm -r $PKG_DIR/opt/Citrix/ICAClient/keystore/cacerts

# more links ...
for ini in `ls $PKG_DIR/etc/icaclient/nls/en/*.ini | xargs -n1 basename`; do
    echo /etc/icaclient/nls/current/${ini} /usr/lib/ICAClient/config/${ini} \
         >> $PKG_DIR/debian/links
done

# move pkg install scripts out of the way for now:
#disable_install_scripts

####
#
# finish it up
#

build_package

drop_result
